version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: qwen2-vl
    IMAGE_TAG: latest
    AWS_DEFAULT_REGION: ap-south-1

phases:

  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_URI/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - docker push $ECR_URI/$IMAGE_REPO_NAME:$IMAGE_TAG